### ISSUE TITLE
Get more results

### ISSUE THREAD

**Issue by soundproofboot** [crosenfrisk/Popcorn#87]
Set up a button when results are delivered to allow the user to click and receive the next page of results, if there are any.

**Comment by crosenfrisk** [comment]
@soundproofboot did we want to close this issue or add it to our list of future enhancements?

**Comment by soundproofboot** [comment]
Ya I'll close it, definitely not gonna get to it at this point.

**Comment by crosenfrisk** [comment]
Sounds good. Thanks Colin. We can earmark it for later dev.
